added image & input
sharmayatendra/Amaze-UI pull request #5
Opened 2022-02-05 19:21 UTC by sharmayatendra

2022-02-05 21:30 UTC, devdeadviz commented on components/Image/image.html
> +
Use proper code formatting.

2022-02-05 21:31 UTC, devdeadviz commented on components/Image/image.html
> +  sandbox="allow-scripts allow-same-origin">
same here

2022-02-05 21:32 UTC, devdeadviz commented on components/Input/input.css
> +}
You can create a common variable style sheet for all the variables.

2022-02-05 21:52 UTC, devdeadviz commented on components/Input/input.html
> +  sandbox="allow-scripts allow-same-origin">
use proper code formatting

2022-02-05 21:52 UTC, devdeadviz requested changes
Added some required changes.

2022-02-06 15:29 UTC, xii-vi approved these changes
Work on the comments. Rest is fine to merge.

2022-02-06 17:35 UTC, merged